### ISSUE TITLE
amp-story-auto-ads not showing ads

### ISSUE THREAD

**Issue by greghuet** [ampproject/amp-by-example#1847]
We are working on releasing a new format for the content of our site using AMP Stories. For this to work, we need to use ads on the integration, therefore, we need to use amp-story-auto-ads. We have implemented it properly, please set the data-slot correctly using Google Ad Manager, but we've never seen an ad. Here is the example page: https://www.mon-horoscope-du-jour.com/story/hq0-belier.php

What are we doing wrong ? Thanks in advance.

**Comment by kul3r4** [comment]
Hi, for questions in general please use stackoverflow in the future as this is a project for samples.

@calebcordry do you have any idea why the ad is not showing?

Moreover when running https://www.mon-horoscope-du-jour.com/story/hq0-belier.php#development=1 I get validator.js:510 https://www.mon-horoscope-du-jour.com/story/hq0-belier.php:18:1 The tag 'AMP-STORY (beta)' is deprecated - use 'AMP-STORY' instead. (see https://www.ampproject.org/docs/reference/components/amp-story#migrating-from-0.1-to-1.0), it would be useful to migrate to 1.0

**Comment by calebcordry** [comment]
@greghuet  amp-story-auto-ads controls placement of the ads. The current algorithm will only place the first ad after the 7th page. It appears this story is too short to receive any ads. Could you try with a longer story?

**Comment by greghuet** [comment]
Hi, thank you so much for your replies. I've been working on a new version with more cards, but still no ads: https://www.mon-horoscope-du-jour.com/story/hq0.php?sign_id=0
Right now, we see requests on the Google Ad Manager report, but without any filling :( Does it takes time to "learn" ? how many impressions before it's unlocked ? Thank you again ;)

**Comment by calebcordry** [comment]
When I try that site I do not see any ad requests being made. Could you also upgrade to the 1.0 version of amp-story?

**Comment by greghuet** [comment]
Thank you Calebcordry for your comment. I've done it, still nothing on display:
https://www.mon-horoscope-du-jour.com/story/hq0.php?sign_id=0

From the report, we see some requests now, but none filled (it's all opened for this ad-slot). Is there some limitations ? Would this work on the French market or is it limited to the English speaking market so far ? Thank you again for your great assistance ;)

**Comment by calebcordry** [comment]
@greghuet Great, I now see the ad request being made from the story, but the response is empty and the ad is not being filled. Unfortunately this has something to do with your ad manager configuration, and I don't know too much about that system. We do have a bot of [documentation here](https://support.google.com/admanager/answer/9038178?hl=en), hope it helps.

**Comment by greghuet** [comment]
Thank you for your message ;) I will check the doc. Also, could you please tell me how do you see the ad request being made from the story ? This will help me a lot for the rest of the dev. Thank you again

**Comment by greghuet** [comment]
Hi again, I've analysed the network calls when the story is loading to highlight the connection with Google Ad Manager, got the tag which displays an empty space. I'll continue my investigation and I'll share here if this help others ;)

**Comment by calebcordry** [comment]
Sorry for the delay, glad you found the network request. That is the same place that I was looking. Please let us know if/when you are able to figure it out.

**Comment by greghuet** [comment]
Hi, so far, I've not been able to show any ads on my AMP Stories. So, I went to check the CNN AMP Stories, to see if I can see any ads, and with my desktop or smartphone (Android), still no chance. Is there some kind of geo-targetting ? Do you see ads on CNN AMP Stories (example: https://edition.cnn.com/ampstories/style/paris-fashion-week-nostalgia-oprah-and-lagerfeld-tributes) ? This would really help me to understand what is going on.
Thanks you all in advance.

**Comment by calebcordry** [comment]
Hey @greghuet that CNN page has `amp-story-auto-ads` enabled, but it does not fill when I look at it. This could be based on a number of factors around targeting, (location, time, interests etc). 

This is the same thing that I see on your test page. The `amp-story-auto-ads` extension makes a request to the ad server but the ad server is not responding with an ad. Unfortunately I can't help too much with this as it is not a part of amp. We do have this doc https://support.google.com/admanager/answer/9038178?hl=en hopefully it helps.

**Comment by greghuet** [comment]
Thank you for your reply and the confirmation you were not able to see any ads on CNN too. So far, my experience with ads on AMP Story is not great cause no matter of the configuration of the ad placement on Google Ad Center, there is nothing to fill the placement. I'll post again here if I found a solution or I'll get a answer from our Google account manager. Thank you all for your support.

**Comment by calebcordry** [comment]
@jasti Do we have any resources to help @greghuet on the ad manager side? He is getting no-fills when he thinks they should be serving ads?

**Comment by jasti** [comment]
@greghuet, currently, there is a programmatic support for AMP story ads from Google Ad Manager. That is, you have to traffic, target and deliver your own direct sold ads from your Google Ad Manager instance (which is what CNN and WaPo are doing). In either case, your suggestion to follow up with the Google Ad Manager support is the right one.

**Comment by greghuet** [comment]
Thanks @jasti for your reply, we will investigate this today. Does it mean that we cannot use Adsense in this placement in AMP Story ? I'm the tech guy, the ad part is done by someone else, therefore it's important he has as much info as possible. Again thank you all ;)

**Comment by jasti** [comment]
Correct, there is no AdSense support at the moment.

**Comment by greghuet** [comment]
Thanks @jasti  for your reply ;) That explains a lot ;) We are working right now on the configuration on Ad Manager to see if we can get some other results in the placement. I think it might be a good idea to indicate somewhere in the documentation that Adsense is not supported in AMP Story auto ads throught Google Ad Center ;)

**Comment by acspeeddev** [comment]
@greghuet Did you ever manage to resolve this? I have the exact same issue as yourself. Everything is installed correctly and triggering but our Google  Ad Manager is set up to deliver AdSense, which as mentioned is not actually supported in auto-amp-story-ads.

Thanks

**Comment by greghuet** [comment]
hi @acspeeddev, we speet countless hours trying to find a solution but nothing works. We have tried the most basic solution by seting up our own promotional ads in Google Ad Manager to be sure that something would be delivered... but it did not... from some exchange, we got some information, like that the story needs to have a minumum set of pages to call the auto-amp-story-ads, and that it normally shows for page 4... When analysing the request from Chrome inspect tools, we see that the calls are done, but the returned content is an empty iframe.

I don't know if this will help you, we are still looking for a solution, it'll be nice if we can share here our experience to finally get to this graal ;)

**Comment by acspeeddev** [comment]
@greghuet it seems we are both having the same issue. It also seems there is a large lack of support for auto-amp-story-ads in terms of ad delivery from all ad networks. We've spent the last 4 weeks searching for amp stories all over the internet and not one has displayed an ad to us (we also check inspect tools to ensure they have the correct scripts/config etc and they all seem to be right). 

I find it very strange Adsense was not a priority support for amp-story-ads and no indication of when it will be supported as this would make our lives so much easier. If we do make any progress or discover an ad network that delivers, I will let you know.

**Comment by greghuet** [comment]
@acspeeddev thank you for your message. We also tried to find some AMP Story with ads, as the ones shown in the example, none of them was working. When I mentionned that, I got "ads must be geotargetted" as an answer (we're based in France). Then I tried using a US VPN (really seen as US IP), still nothing... 

I personnaly think that the AMP Story is a great solution to show content, and to make the whole experience easier on the dev site, why not using Adsense ? This is a no brainer... Only large sites / experts are using Google Ads Center, it takes time to feel confortable with all notions and with the interface. Fortunately for us, we do have an expert in-house... 

For the AMPProject developers, could you please let us now what is the future of auto-amp-story-ads in relation with Adsense ?

Thank you all

**Comment by acspeeddev** [comment]
@greghuet could not agree more. AMP Story's are amazing and we've had an incredible response to the story's we have published so far so we intend to invest long term in this format. Hopefully a simple AdSense support solution is coming soon! Good luck et Bonne journée ;)

**Comment by acspeeddev** [comment]
@greghuet could not agree more. AMP Story's are amazing and we've had an incredible response to the story's we have published so far so we intend to invest long term in this format. Hopefully a simple AdSense support solution is coming soon! Good luck et Bonne journée ;)

**Comment by calebcordry** [comment]
@greghuet @acspeeddev Thanks for the feedback. Unfortunately adsense is still not supported. The only ad network that is currently supported is doubleclick. We have it [listed here](https://amp.dev/documentation/guides-and-tutorials/develop/advertise_amp_stories/#integrate-ad-server-support) in the docs, but let me know if you were looking somewhere else it should be added. We are actively working on adsense support and hope to have it launched ASAP. We will be sure to make an announcement when it is ready.

**Comment by acspeeddev** [comment]
@calebcordry Thanks for the reply. The documentation you refer to is exactly what we have set up on our amp stories but with AdSense selected as the Ad Network (via Google Ad Manager). As there are many ad networks to select, how do we know which are supported in amp-story when selecting an Ad Network? Or am I completely missing something here? 

I think the placement of the information isn't the issue (for me anyway) it's the title of it (Integrate Ad Server Support) I was searching for something such as _Ad Networks for Amp Story via Google Ad Manager_. I can't  actually see anywhere in the docs where it states AdSense is not supported and I naturally assumed it would be, the same as @greghuet , so I think this is the most confusing aspect of it.  As I understand, doubleclick, is the Ad Server, not the network? Thanks again for your help.

**Comment by calebcordry** [comment]
I think this naming got a bit more confusing when Google rolled everything under "Google Ad Manager". Maybe it would be more correct to say, currently we only support direct sold creatives trafficked through Google ad manager (historically was doubleclick). I will think a bit about how to make this more clear in the docs.

You can not currently serve any adsense demand into amp stories (yet). Hopefully that clears things up.

**Comment by acspeeddev** [comment]
@calebcordry YES! That literally now makes everything clear! **only support direct sold creatives trafficked through Google ad manager** That perfectly explains the support in place for advertising in amp-story via Google Ad Manager as it is right now. Thanks for clearing this up. Will look forward to AdSense being supported in the future at some point.
